---

- name: render_zookeeper_systemd_service_conf
  template:
    src: "templates/confluent_zookeeper/zookeeper.service.j2"
    dest: "/lib/systemd/system/{{ item.static.service_name }}.service"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - "{{ zookeeper.service }}"
  register: systemd_service_conf


- name: enable_zookeeper_service_and_daemon_reload
  systemd:
    name: "{{ item.static.service_name }}.service"
    enabled: yes
    daemon_reload: yes
  with_items:
    - "{{ zookeeper.service }}"


- name: start_zookeeper_service
  systemd:
    name: "{{ zookeeper.service.static.service_name }}"
    enabled: true
    state: started



# HEALTHCHECK
- name: install_nmap_for_zookeeper_check
  apt:
   name: nmap
   state: present


- name: pause_15_seconds
  pause:
    seconds: 15


- name: check_which_zookeeper_node_is_leader/follower
  shell: echo stat | nc {{ zookeeper_host.stdout }} 2181 | grep Mode


- name: check_zookeeper_server_status
  shell: echo srvr | nc {{ zookeeper_host.stdout }} 2181


- name: check_zookeeper_connections
  shell: echo cons | nc {{ zookeeper_host.stdout }} 2181

