---

- name: render_schema-registry_systemd_service_conf
  template:
    src: "templates/confluent_schemaregistry/schema-registry.service.j2"
    dest: "/lib/systemd/system/{{ item.static.service_name }}.service"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - "{{ schemaregistry.service }}"
  register: systemd_service_conf


- name: enable_schema-registry_service_and_daemon_reload
  systemd:
    name: "{{ item.static.service_name }}.service"
    enabled: yes
    daemon_reload: yes
  with_items:
    - "{{ schemaregistry.service }}"


- name: start_schema-registry_service
  systemd:
    name: "{{ schemaregistry.service.static.service_name }}"
    enabled: true
    state: started


- name: pause_15_seconds
  pause:
    seconds: 15


  # unknown topic issue - https://stackoverflow.com/questions/58741157/
- name: restart_schema-registry_service
  systemd:
    name: "{{ item.static.service_name }}.service"
    state: restarted
  with_items:
    - "{{ schemaregistry.service }}"