- hosts: "{{ confluentTarget }}" #confluent
  become: True
  become_method: sudo
  gather_facts: True

  vars_prompt:
    - name: "confluentTarget"
      prompt: "Please enter confluent target hosts"
      private: no

  roles:
    - confluent_destroy